version: "3.7"

services:
    django:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        image: app:hermes-test
        container_name: hermes
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db_volume:/var/lib/postgresql/data
        container_name: pgdb

volumes:
  db_volume:
    external: true