# Generated by Django 3.2.13 on 2022-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('published', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='date_finish',
            field=models.DateField(),
        ),
    ]
