# Generated by Django 3.2.13 on 2022-09-30 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20220927_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='home.record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
