# Generated by Django 3.2.13 on 2022-10-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20220930_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='published_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='auth.user'),
            preserve_default=False,
        ),
    ]
