# Generated by Django 3.2.13 on 2022-10-19 08:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20221001_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_type', models.CharField(choices=[('AIRPORT', 'AIRPORT'), ('BE', 'BE'), ('OTHER', 'OTHER')], default='AIRPORT', max_length=20)),
                ('network', models.CharField(default='ALL', max_length=20)),
                ('manual', models.FileField(blank=True, null=True, upload_to='upload-manuals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'txt', 'ppt', 'pptx'])])),
                ('short_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
