# Generated by Django 3.2.13 on 2022-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='name',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
