# Generated by Django 3.2.13 on 2022-10-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_manual_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual',
            old_name='manual',
            new_name='man_file',
        ),
    ]
