# Generated by Django 3.2.13 on 2022-11-17 14:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userhermes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhermes',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
