# Generated by Django 3.2.13 on 2022-12-05 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_alter_userhermes_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhermes',
            name='id',
        ),
        migrations.AlterField(
            model_name='userhermes',
            name='user',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
