# Generated by Django 3.2.13 on 2022-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_lastmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lastMessage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
