# Generated by Django 3.2.13 on 2022-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_lastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isPrivate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
